server:
  port: 8080

spring:
  application:
    name: ping-service
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
        username: nacos
        password: Config@y2t-107